# Generated by Django 2.2.6 on 2019-10-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_buddy_app', '0002_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(on_delete='cascade', related_name='created_trips', to='trip_buddy_app.User'),
        ),
    ]
